app_report/urls.py
from django.urls import path
from . import views

app_name='app_report'
urlpatterns = [
    path('', views.index, name='index'),
    path('view/<str:Schedule_id>', views.view, name='view'),
    path('maps/<str:Schedule_id>/<str:Vehicle_id>', views.maps, name='maps'),
    path('add-outlet/<str:Schedule_id>/<str:Vehicle_id>', views.add, name='add'),
    path('selected-outlets/process-outlets/', views.processoutlets, name='processoutlets'),
    path('new-schedule/result', views.result, name='result'),
    path('delete/<str:Schedule_id>', views.delete, name='delete')
]

proweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', redirect('home/')),
    path('schedule/', include('app_schedules.urls', namespace='app_schedules')),
    path('vehicle/', include('app_vehicle.urls', namespace='app_vehicle')),
    path('outlet/', include('app_outlet.urls', namespace='app_outlet')),
    path('report/', include('app_report.urls', namespace='app_report')),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_dashboard.urls')),        #home
    path('admin/', admin.site.urls),
]

app_report/models.py
from django.db import models
from app_schedules.models import ScheduleModel

# Create your models here.

class Map(models.Model):
    name = models.CharField(max_length=255)
    Schedule = models.ForeignKey(ScheduleModel, on_delete=models.CASCADE, related_name='maps', default='Schedule_id')
    file_path = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

app_report/forms.py
from django import forms
from app_schedules.models import ScheduleOutlet

class StatusForm(forms.ModelForm):
    StatusChoices=(
        ('Finish', 'Finish'),
        ('On Progress', 'On Progress'),
    )
    Status = forms.ChoiceField(
        choices=StatusChoices,
        required=False,
        widget=forms.Select(
            attrs={
                'class' :'form-select form-control'
            }
        )
    )
    class Meta:
        model=ScheduleOutlet
        fields = [
            'Status',
        ]

app_report/views.py
import os
import json
import pytz
import folium
import polyline
import pandas as pd
from .forms import StatusForm
from app_schedules.algorithm.GA import GeneticAlgorithm 
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.staticfiles import finders
from django.contrib import messages
from django.db.models import Case, When
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from app_schedules.models import ScheduleModel, ScheduleOutlet, ScheduleVehicle
from app_vehicle.models import VehicleModel
from app_outlet.models import OutletModel
from app_report.models import Map
from django.db.models import Q
from django.utils import timezone
from django.utils.timezone import make_naive
from proweb.decorators import group_required
# Create your views here.
@group_required('Admin', 'Driver')
def index(request):
    ScheduleObject = ScheduleModel.objects.all()
    # Konversi waktu UTC ke zona waktu lokal pengguna
    display_timezone = pytz.timezone('Asia/Makassar')
    for item in ScheduleObject:
        print(f"UTC Time: {item.Created_at}, Local Time: {item.Created_at.astimezone(display_timezone)}")
        
        # item.Created_at = item.Created_at.astimezone(display_timezone)
        item.Created_at = make_naive(item.Created_at, display_timezone)
        print(item.Created_at)
    print('')
    for item in ScheduleObject:
        print(item.Created_at)
    context = {
        'ScheduleObject' : ScheduleObject,
    }
    print(context)
    return render(request, 'report/index.html', context)

@group_required('Admin', 'Driver')
def maps(request, Schedule_id, Vehicle_id):
    
    existing_map = Map.objects.filter(name=f'{Schedule_id}-{Vehicle_id}').first()
    if existing_map:
        # Jika sudah ada, kembalikan file path atau response sesuai kebutuhan
        return render(request, f'maps/{Schedule_id}-{Vehicle_id}.html')
    else:
        ScheduleObject = ScheduleOutlet.objects.filter( Q(Group_vehicle_number=Vehicle_id) & Q(Schedule_id=Schedule_id)).order_by('id')
        AllRoute=[]
        for iteration in range(len(ScheduleObject)-1):
            firstKey = ScheduleObject.values_list('OutletCode', flat=True)[iteration]
            secondKey = ScheduleObject.values_list('OutletCode', flat=True)[iteration+1]
            AllRoute.append(f'{firstKey}, {secondKey}')
        # print(Route)
        
        json_file_path = finders.find('files/distanceMatrix.json')
        data = {}
        if json_file_path:
            with open(json_file_path, 'r') as json_file:
                data = json.load(json_file)
                
        start_route = AllRoute[0]
        start_location = [data[start_route]['from']['outlet_coord'][1], data[start_route]['from']['outlet_coord'][0]]
        result_map = folium.Map(location=start_location, zoom_start=12)

        # Loop hanya melalui rute yang dipilih
        
        i=0
        for key in AllRoute:
            if key in data:
                location_to = OutletModel.objects.filter(OutletCode=data[key]['to']['outlet_code']).values_list('OutletName', flat=True).first()
                location_from = OutletModel.objects.filter(OutletCode=data[key]['from']['outlet_code']).values_list('OutletName', flat=True).first()
                
                route_data = data[key]
                from_coord = route_data['from']['outlet_coord']
                from_coord = [from_coord[1], from_coord[0]]
                
                to_coord = route_data['to']['outlet_coord']
                to_coord = [to_coord[1], to_coord[0]]
                
                if i == 0:
                    folium.Marker(
                        location = from_coord,
                        popup=folium.Popup( f"""Start : {location_from}""",max_width=500),
                    ).add_to(result_map)
                    
                folium.Marker(
                    location = from_coord,
                    popup=folium.Popup( f"""From: {location_from} - To: {location_to}""",max_width=500),
                    icon=folium.DivIcon(html=f"""<div style="font-size: 20pt; font-weight: bold; color: black">{i}</div>""")
                ).add_to(result_map)
                
                folium.Marker(
                    location = to_coord,
                    popup=folium.Popup( f"""From: {location_from} - To: {location_to}""",max_width=500),
                ).add_to(result_map)
                
                if i==len(AllRoute)-1:
                    folium.Marker(
                        location = to_coord,
                        icon=folium.DivIcon(html=f"""<div style="font-size: 20pt; font-weight: bold; color: black">{i+1}</div>""")
                    ).add_to(result_map)
                    
                # Decode geometri polyline dan tambahkan ke peta sebagai PolyLine
                encoded_geometri = route_data['geometri']
                decoded_coords = polyline.decode(encoded_geometri)
                
                # Tambahkan rute ke peta
                folium.PolyLine(decoded_coords, color="blue", weight=2.5, opacity=1).add_to(result_map)
            i+=1
            
            file_path = os.path.join('app_report', 'templates', 'maps', f'{Schedule_id}-{Vehicle_id}.html')
            
        # Simpan peta ke file HTML
        result_map.save(file_path)
        Map.objects.create(name=f'{Schedule_id}-{Vehicle_id}', Schedule_id=Schedule_id, file_path=file_path)
        return render(request, f'maps/{Schedule_id}-{Vehicle_id}.html')
        # return redirect(reverse('app_report:view', kwargs={'Schedule_id':Schedule_id}))

@group_required('Admin', 'Driver')
def view(request, Schedule_id):
    # Retrieve data for view page section
    VehicleSchedule = ScheduleVehicle.objects.filter(Schedule_id=Schedule_id)
    
    json_file_path = finders.find('files/distanceMatrix.json')
    data = {}
    if json_file_path:
        with open(json_file_path, 'r') as json_file:
            data = json.load(json_file)
            
    RouteListed={}
    for vehicle in VehicleSchedule:
        key = vehicle.VehicleNumber_id
        ScheduleObject = ScheduleOutlet.objects.filter(
            Q(Group_vehicle_number=key) & Q(Schedule_id=Schedule_id)).order_by('id')
        vehicleObject = VehicleModel.objects.get(VehicleNumber=key)
        RouteListed[key] = {
            'NumberLocation':vehicle.Total_location_each_vehicle, 
            'detailsVehicle':{
                'ScheduleId' : Schedule_id,
                'VehicleNumber' : vehicleObject.VehicleNumber,
                'VehicleType' : vehicleObject.UnitType,
                'DriverName' : vehicleObject.DriverName,
                'TotalDistance' : vehicle.Total_distance_each_vehicle,
                'TotalOutlets' : vehicle.Total_location_each_vehicle
            }
        }
        if 'detailsRoute' not in RouteListed[key]:
            RouteListed[key]['detailsRoute'] = {}
        for iteration in range(len(ScheduleObject)-1):
            firstKey = ScheduleObject.values_list('OutletCode', flat=True)[iteration]
            secondKey = ScheduleObject.values_list('OutletCode', flat=True)[iteration+1]
            statusRoute = ScheduleObject.values_list('Status', flat=True)[iteration+1]
            
            firstOutlet = OutletModel.objects.get(OutletCode=firstKey).OutletName
            secondOutlet = OutletModel.objects.get(OutletCode=secondKey).OutletName
            
            firstOutlet_Address = OutletModel.objects.get(OutletCode=firstKey).Address
            secondOutlet_Address = OutletModel.objects.get(OutletCode=secondKey).Address
            
            searchedKey = f'{firstKey}, {secondKey}'
            FilteredDict = {key: value for key, value in data.items() if key == searchedKey}
            distance = FilteredDict.get(searchedKey, {})
            distance = distance.get('jarak')
            RouteListed[key]['detailsRoute'][searchedKey]={
                'firstOutlet' : firstOutlet,
                'secondOutlet' : secondOutlet,
                'secondCode' : secondKey,
                'from_address' : firstOutlet_Address,
                'to_address' : secondOutlet_Address,
                'distance' : distance,
                'status' : statusRoute
            }
            
    # Change Status Section
    statusForm = StatusForm(request.POST or None)
    error = None
    if request.method == 'POST':
        if statusForm.is_valid():
            selected_outlets_data = request.POST.get("selected-outlets")
            # Parse JSON string menjadi list of dictionaries
            print(selected_outlets_data)
            status = statusForm.cleaned_data['Status']
            try:
                selected_outlets = json.loads(selected_outlets_data)
            except json.JSONDecodeError:
                print('error')
                return JsonResponse({"error": "Invalid JSON format"}, status=400)
            if not selected_outlets_data:
                print('Error: No outlets selected')
                messages.error(request, "You must select at least one outlet.")
                return redirect('your_view_name')
            # Loop untuk memproses setiap outlet yang dipilih
            for outlet_data in selected_outlets:
                vehicle_id = outlet_data.get("vehicleId")
                schedule_id = outlet_data.get("scheduleId")
                selected_outlet_ids = outlet_data.get("selectedOutlets", [])

                # Proses untuk mengupdate status berdasarkan vehicle_id, schedule_id, dan outlet yang dipilih
                # Misalnya, Anda mencari record di database dan mengubah statusnya
                # Pastikan model dan field sesuai dengan data yang Anda miliki
                ScheduleOutlet.objects.filter(
                    Group_vehicle_number=vehicle_id,
                    Schedule_id=schedule_id,

app_report/templates/report/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load custom_tags %}

{% block style_app %}
<style>
  .text-center {
    text-align: center;
    vertical-align: middle;
  }
  .large-checkbox {
    width: 20px;
    height: 20px;
  }
  table th, td{
    text-align: center;
    vertical-align: middle;
  }
  table td .btn{
    width: 100%;
    margin: 0
  }
  table td .btn:nth-child(2){
    margin:0px 10px;
  }
</style>
{% endblock style_app %}

{% block content_header %}
<div class="page-header">
  <h3 class="fw-bold mb-3">Report</h3>
  <ul class="breadcrumbs mb-3">
    <li class="nav-home">
      <a href="{% url breadcrumbs.dashboard.url %}">
        <i class="icon-home"></i>
      </a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a href="{% url breadcrumbs.report.index.url %}">{{breadcrumbs.report.index.name}}</a>
    </li>
  </ul>
  <!-- <button id="generate-schedule-btn" class="btn btn-secondary btn-round ms-auto">
    Finish
  </button> -->
</div>
{% endblock content_header %}

{% block Content %}
{% comment %} Vehicle Table {% endcomment %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <h4 class="card-title">List of Reports</h4>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">            
          <table id="add-row" class="display table table-striped table-hover" >
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">ScheduleCode</th>
                <th scope="col">Date Created</th>
                <th scope="col">Time Created</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for ScheduleDatas in ScheduleObject %}
              <tr>
                <td scope="'row">{{forloop.counter}}</td>
                <td>{{ScheduleDatas.Schedule_id}}</td>
                <td>{{ScheduleDatas.Created_at|date:"F j, Y"}}</td>
                <td>{{ScheduleDatas.Created_at|date:"g:i a" }}</td>
                <td>
                  <div class="form-button-action">
                    <a href="{% url 'app_report:view' Schedule_id=ScheduleDatas.Schedule_id %}" class="btn btn-secondary">
                      View
                    </a>
                    {% if user|has_group:"Admin" %}
                      <button 
                        type="button" 
                        class="btn btn-danger" 
                        data-bs-toggle="modal" 
                        data-bs-target="#deleteModal" 
                        data-url="{% url 'app_report:delete' Schedule_id=ScheduleDatas.Schedule_id %}">
                        Delete
                      </button>
                    {%endif%}
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Konfirmasi Hapus -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Konfirmasi Penghapusan</h5>
          </div>
          <div class="modal-body">
              Apakah Anda yakin ingin menghapus data ini? Tindakan ini tidak dapat dibatalkan.
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tidak</button>
              <button type="button" class="btn btn-danger" id="confirmDelete">Ya, Hapus</button>
          </div>
      </div>
  </div>
</div>

{% endblock Content %}

{% block scripts_app %}
<!-- Datatables -->
<script src="{% static '/assets/js/plugin/datatables/datatables.min.js' %}"></script>
<script>
  $(document).ready(function () {
    var deleteUrl = '';

    // Atur URL hapus saat modal ditampilkan
    document.getElementById('deleteModal').addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Tombol yang memicu modal
        deleteUrl = button.getAttribute('data-url'); // Mengambil data-url dari tombol
    });

    // Hapus data saat pengguna mengkonfirmasi
    document.getElementById('confirmDelete').addEventListener('click', function() {
        window.location.href = deleteUrl;
    });

    $("#basic-datatables").DataTable({});
    $("#add-row").DataTable({});

  });
  </script>
{% endblock scripts_app %}

app_report/templates/report/view.html
{% extends "layout/base.html" %}
{% load static %}
{% load custom_tags %}

{% block style_app %}
<style>
  .text-center {
    text-align: center;
    vertical-align: middle;
  }
  .large-checkbox {
    width: 20px;
    height: 20px;
  }
</style>
{% endblock style_app %}

{% block content_header %}
<div class="page-header">
  <h3 class="fw-bold mb-3">Report</h3>
  <ul class="breadcrumbs mb-3">
    <li class="nav-home">
      <a href="{% url breadcrumbs.dashboard.url %}">
        <i class="icon-home"></i>
      </a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a href="{% url breadcrumbs.report.index.url %}">{{breadcrumbs.report.index.name}}</a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a>{{breadcrumbs.report.view.name}}</a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a>{{Schedule_id}}</a>
    </li>
  </ul>
</div>
{% endblock content_header %}

{% block Content %}
{% comment %} Outlet Table {% endcomment %}
<div class="card">
  <div class="card-header">
    <div class="d-flex align-items-center">
      <h4 class="card-title">Delivery Table</h4>
      {% if user|has_group:"Admin" %}
      
      <!-- <div class="tab-content ms-auto" id="myTabContent">
        {% for key, subkey in RouteListed.items %}
          <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="tab-{{ forloop.counter }}" role="tabpanel" aria-labelledby="tab-{{ forloop.counter }}-tab">
          
            <a href="{% url 'app_report:add' Schedule_id=subkey.detailsVehicle.ScheduleId Vehicle_id=subkey.detailsVehicle.VehicleNumber %}">
              <button class="btn btn-secondary" >
                <i class="fa fa-plus"></i>
                Add new outlet
              </button>
            </a>
          </div>
        {%endfor%}
      </div> -->

      <!-- <button 
          type="button" 
          class="btn btn-secondary ms-auto" 
          data-bs-toggle="modal" 
          data-bs-target="#addOutlet" >
          
          <i class="fa fa-plus"></i>
          
      </button> -->
      {%endif%}
    </div>
  </div>

  <div class="container">
    <br>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        {% for key, subkey in RouteListed.items %}
        <li class="nav-item" role="presentation">
            <button 
              class="nav-link {% if forloop.first %}active{% endif %}" 
              id="tab-{{ forloop.counter }}-tab" 
              data-bs-toggle="tab" 
              data-bs-target="#tab-{{ forloop.counter }}" 
              type="button" 
              role="tab" 
              aria-controls="tab-{{ forloop.counter }}" 
              aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">

            <span>Route {{forloop.counter}}</span>
            </button>
        </li>
        {% endfor %}
    </ul>

    <!-- Tab content -->
    <div class="tab-content" id="myTabContent">
      {% for key, subkey in RouteListed.items %}
      <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="tab-{{ forloop.counter }}" role="tabpanel" aria-labelledby="tab-{{ forloop.counter }}-tab">
        <div class="card-header">
          <h3 class="text-center">Route {{forloop.counter}}</h3>
          <p class="my-0">There are {{subkey.detailsVehicle.TotalOutlets}} locations to go with a total distance of {{subkey.detailsVehicle.TotalDistance|floatformat:3}} Km </p>
          <br>
          <div class="row">
            <div class="col-md-6">
              <div class="d-flex flex-column">
                <span>Vehicle Type : {{subkey.detailsVehicle.VehicleType}}</span>
                <span>Vehicle Number : {{subkey.detailsVehicle.VehicleNumber}}</span>
                <span>Driver : {{subkey.detailsVehicle.DriverName}}</span>
              </div>
            </div>
            <div class="col-md-6">
              <div class="d-flex justify-content-between">
              
                <button 
                    type="button" 
                    class="btn btn-secondary" 
                    style="width: 45%;"
                    data-bs-toggle="modal" 
                    data-bs-target="#changeStatus" >
                    Change Delivery Status
                </button>
                
                <a href="{% url 'app_report:maps' Schedule_id=subkey.detailsVehicle.ScheduleId Vehicle_id=subkey.detailsVehicle.VehicleNumber%}" class="btn btn-success" style="width: 45%;">
                  Maps
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">          
            <table 
                id="basic-datatables-{{ forloop.counter }}" 
                class="display table table-striped table-hover" 
                data-vehicle-id = "{{subkey.detailsVehicle.VehicleNumber}}"
                data-schedule-id = "{{subkey.detailsVehicle.ScheduleId}}">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th>
                    <input type="checkbox" id="select-all" class="select-all">
                  </th>
                  <th>From </th>
                  <th>Address </th>
                  
                  <th>To</th>
                  <th>Address </th>

                  <th>Distance</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% for outletskey, value in subkey.detailsRoute.items %}
                  <tr>
                    <td scope="'row">{{forloop.counter}}</td>
                    <td>
                      <input type="checkbox" class="item-checkbox" value="{{ value.secondCode }}">
                    </td>
                    <td>{{value.firstOutlet}}</td>
                    <td>{{value.from_address}}</td>
                    <td>{{value.secondOutlet}}</td>
                    <td>{{value.to_address}}</td>
                    <td>{{value.distance|floatformat:3}} KM</td>
                    <td>
                      <span class="badge"> {{value.status}}</span>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<!-- Modal Ganti Status -->
<div class="modal fade" id="changeStatus" tabindex="-1" aria-labelledby="changeStatusLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="changeStatusLabel">Ganti Status Pengiriman</h5>
          </div>
          <form method="post" id="updateForm" class="updateForm">
            <div class="modal-body">
                {% csrf_token %}
                <div class="mt-3 mb-3">
                  <label>Pilih Status:</label>
                  <input type="hidden" id="selected-outlets" class="selected-outlets" name="selected-outlets">
                      {{ form.Status }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-secondary" id="updateButton">Update Status</button>
            </div>
            
          </form>
      </div>
  </div>
</div>

<!-- Modal Tambah Toko -->
<div class="modal fade" id="addOutlet" tabindex="-1" aria-labelledby="changeStatusLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="changeStatusLabel">Add Outlet</h5>
          </div>
          <!-- <form method="post" id="updateForm" class="updateForm">
            <div class="modal-body">
                {% csrf_token %}
                <div class="mt-3 mb-3">
                  <label>Pilih Status:</label>
                  <input type="hidden" id="selected-outlets" class="selected-outlets" name="selected-outlets">
                      {{ form.Status }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-secondary" id="updateButton">Update Status</button>
            </div>
            
          </form> -->
      </div>
  </div>
</div>
{% endblock Content %}

{% block scripts_app %}
<!-- Datatables -->
<script src="{% static '/assets/js/plugin/datatables/datatables.min.js' %}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/select/1.7.0/js/dataTables.select.min.js"></script>
<script>
  $(document).ready(function() {
    
    $("#basic-datatables-1").DataTable({
      "drawCallback": function( settings ) {
        const tds = document.querySelectorAll('span.badge');
        tds.forEach(td => {
          const text = td.textContent.trim().toLowerCase();
          switch (text) {
              case 'finish':
                  td.className = 'badge badge-success';
                  break;
              case 'on progress':
                  td.className = 'badge badge-warning';
                  break;
              default:
                  td.className = 'badge badge-default';
          }
        });
      }
    });


    // Event listener for tab change
    $('button[data-bs-toggle="tab"]').on('shown.bs.tab', function (e) {
      var targetId = $(e.target).data('bs-target'); // Get target tab ID
      var tableId = $(targetId).find('table').attr('id'); // Get the table ID in the active tab
      // Initialize DataTable if it hasn't been initialized already
      if (!$.fn.DataTable.isDataTable('#' + tableId)) {
          $('#' + tableId).DataTable();
      }
    });

    // Clear session storage on page load
    sessionStorage.clear(); 
    $('input[type="checkbox"]').prop('checked', false);

    // Restore checked checkboxes from session storage
    //$('input[type="checkbox"]').each(function() {
    //    var id = $(this).val();
    //    if (sessionStorage.getItem(id)) {
    //        $(this).prop('checked', true);
    //    }
    //});
    
    // Checkbox "select all" functionality
    $(document).on('change', '.select-all', function() {
        var isChecked = $(this).is(':checked');
        var table = $(this).closest('table');

        table.find('.item-checkbox').each(function() {
            $(this).prop('checked', isChecked).trigger('change');
        });
    });

    var allSelectedOutletsData = [];
    // Event listener for checkbox changes to track selected outlets across tabs
    $(document).on('change', 'input.item-checkbox', function() {
      var table = $(this).closest('table');
      var vehicleId = table.data('vehicle-id');
      var scheduleId = table.data('schedule-id');
      var outletId = $(this).val();

      // Find or create entry for the current table (vehicleId)
      var entry = allSelectedOutletsData.find(data => data.vehicleId === vehicleId);

      if (!entry) {
          entry = {
              vehicleId: vehicleId,
              scheduleId: scheduleId,
              selectedOutlets: []
          };
          allSelectedOutletsData.push(entry);
      }

      // Add or remove outlet ID from the selectedOutlets array
      if ($(this).is(':checked')) {
          if (!entry.selectedOutlets.includes(outletId)) {
              entry.selectedOutlets.push(outletId);
          }
      } else {
          entry.selectedOutlets = entry.selectedOutlets.filter(id => id !== outletId);
      
          // Jika selectedOutlets kosong setelah penghapusan, hapus seluruh objek
          if (entry.selectedOutlets.length === 0) {
            allSelectedOutletsData = allSelectedOutletsData.filter(entry => entry.vehicleId !== vehicleId);
          }
      }
    });

    // Handle form submission for any tab
    $('.updateForm').on('submit', function(e) {
      e.preventDefault(); // Prevent the default form submission
      // Jika tidak ada data yang dipilih, kirimkan array kosong untuk mencegah error
      //if (allSelectedOutletsData.length === 0) {
      //  allSelectedOutletsData.push({
      //      scheduleId: null,
      //      vehicleId: null,
      //      selectedOutlets: []
      //  });
      //}
      // Update the hidden input with the combined data from allSelectedOutletsData
      $(this).find('.selected-outlets').val(JSON.stringify(allSelectedOutletsData));

      // Submit the form
      this.submit();
    });
});
</script>
{% endblock scripts_app %}