app_outlet/urls.py
from django.urls import path
from . import views

app_name="app_outlet"
urlpatterns = [
    path('', views.outlet_index, name='outletIndex'),
    path('create/', views.outlet_create, name='outletCreate'),
    path('update/<str:outletCode>', views.outlet_update, name='outletUpdate'),
    path('view/<str:outletCode>', views.outlet_view, name='outletView'),
    path('delete/<str:outletCode>', views.outlet_delete, name='outletDelete'),
]

proweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', redirect('home/')),
    path('schedule/', include('app_schedules.urls', namespace='app_schedules')),
    path('vehicle/', include('app_vehicle.urls', namespace='app_vehicle')),
    path('outlet/', include('app_outlet.urls', namespace='app_outlet')),
    path('report/', include('app_report.urls', namespace='app_report')),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_dashboard.urls')),        #home
    path('admin/', admin.site.urls),
]

app_outlet/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

    
class OutletModel(models.Model):
    OutletCode=models.CharField(
        max_length=255,
        primary_key=True
    )
    OutletNumber=models.CharField(
        max_length=255
    )
    OutletName=models.CharField(
        max_length=255
    )
    OutletType=models.CharField(
        max_length=255,
        null=True
    )
    Address=models.CharField(
        max_length=255
    )
    Provinsi=models.CharField(
        max_length=255
    )
    Kabupaten=models.CharField(
        max_length=255
    )
    Kecamatan=models.CharField(
        max_length=255
    )
    Kelurahan=models.CharField(
        max_length=255
    )
    Latitude=models.CharField(
        max_length=255
    )
    Longitude=models.CharField(
        max_length=255
    )
    Days=models.CharField(
        max_length=255
    )
    Delivery=models.CharField(
        max_length=255
    )
    Created_at=models.DateTimeField(
        auto_now_add=True
    )
    Updated_at=models.DateTimeField(
        auto_now=True
    )

# class reg_Provinces(models.Model):
#     name=models.CharField(
#         max_length=255
#     )
#     def __str__(self):
#         return self.name
    
# class reg_Regencies(models.Model):
#     province=models.ForeignKey(reg_Provinces, on_delete=models.CASCADE)
#     name=models.CharField(
#         max_length=255
#     )
#     def __str__(self):
#         return self.name

# class reg_Districts(models.Model):
#     regency=models.ForeignKey(reg_Regencies, on_delete=models.CASCADE)
#     name=models.CharField(
#         max_length=255
#     )
#     def __str__(self):
#         return self.name
    
# class reg_Villages(models.Model):
#     district=models.ForeignKey(reg_Districts, on_delete=models.CASCADE)
#     name=models.CharField(
#         max_length=255
#     )
#     def __str__(self):
#         return self.name

app_outlet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import OutletModel
from .form import OutletForm
from proweb.decorators import group_required

# Create your views here.
# Outlet Views
@group_required('Admin', 'Driver')
def outlet_index(request):
    OutletObject = OutletModel.objects.all()
    context={
        'PageHeader' : 'Outlet Review',
        'link':'app_outlet:outletCreate',
        'linkButton' : 'Add Outlet',
        'OutletDatas' : OutletObject
    }
    return render(request, 'outlet/index.html', context)

@group_required('Admin')
def outlet_create(request):
    OutletForm_Create = OutletForm(request.POST or None)
    error = None
    if request.method == 'POST':
        print(request.POST)
        if OutletForm_Create.is_valid():
            OutletForm_Create.save()
            return redirect('app_outlet:outletIndex')
        else:
            error = OutletForm_Create.errors
    context={
        'pageHeader' : 'Add Outlet',
        'form' : OutletForm,
        'error' : error
    }
    return render(request, 'outlet/create.html', context)

@group_required('Admin')
def outlet_update(request, outletCode):
    updated_data = get_object_or_404(OutletModel, OutletCode = outletCode)
    OutletForm_updated = OutletForm(request.POST or None, instance=updated_data)
    error = None
    if request.method == 'POST':
        if OutletForm_updated.is_valid():
            OutletForm_updated.save()
            return redirect('app_outlet:outletIndex')
    else:
        error= OutletForm_updated.errors
    context = {
        'pageHeader' : 'Update Outlet',
        'form' : OutletForm_updated,
        'error' : error,
    }
    return render(request, 'outlet/update.html', context)

@group_required('Admin', 'Driver')
def outlet_view(request, outletCode):
    selected_data = get_object_or_404(OutletModel, OutletCode = outletCode)
    OutletForm_selected = OutletForm(instance=selected_data)
    for field in OutletForm_selected.fields.values():
        field.widget.attrs['disabled'] = 'disabled'
    
    context = {
        'pageHeader' : 'View Outlet',
        'form' : OutletForm_selected
    }
    return render(request, 'outlet/view.html', context)

@group_required('Admin')
def outlet_delete(request, outletCode):
    OutletModel.objects.filter(OutletCode=outletCode).delete()
    return redirect('app_outlet:outletIndex')

# # Loations Views
# def load_regencies(request):
#     province_id = request.GET.get('Provinsi')
#     regencies = reg_Regencies.objects.filter(province_id=province_id).order_by('name')
#     return JsonResponse(list(regencies.values('id', 'name')), safe=False)

# def load_districts(request):
#     regency_id = request.GET.get('Kabupaten')
#     districts = reg_Districts.objects.filter(regency_id=regency_id).order_by('name')
#     return JsonResponse(list(districts.values('id', 'name')), safe=False)

# def load_villages(request):
#     district_id = request.GET.get('Kecamatan')
#     villages = reg_Villages.objects.filter(district_id=district_id).order_by('name')
#     return JsonResponse(list(villages.values('id', 'name')), safe=False)

app_outlet/templates/outlet/create.html
{% extends "layout/base.html" %}
{% load static %}

{% block content_header %}
<div class="page-header">
    <h3 class="fw-bold mb-3">Add Outlet</h3>
    <ul class="breadcrumbs mb-3">
      <li class="nav-home">
        <a href="{% url breadcrumbs.dashboard.url %}">
          <i class="icon-home"></i>
        </a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="{% url breadcrumbs.outlet.index.url %}">{{breadcrumbs.outlet.index.name}}</a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a>{{breadcrumbs.outlet.add.name}}</a>
      </li>
    </ul>
  </div>
{% endblock content_header %}

{% block Content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">Form Add Outlet</div>
        </div>
        <div class="card-body">
          <form action="" method="POST">
            <div class="row">
              {% csrf_token %}
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>General Info</b></label>
                  <div class="form-group">
                    {{form.OutletNumber.label}}
                    {{form.OutletNumber}}
                    {% if error.OutletNumber %}
                      {% for error in error.OutletNumber %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletCode.label}}
                    {{form.OutletCode}}
                    {% if error.OutletCode %}
                      {% for error in error.OutletCode %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletName.label}}
                    {{form.OutletName}}
                    {% if error.OutletName %}
                      {% for error in error.OutletName %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletType.label}}
                    {{form.OutletType}}
                    {% if error.OutletType %}
                      {% for error in error.OutletType %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <!-- <div class="form-group">
                    {{form.Town.label}}
                    {{form.Town}}
                    {% if error.Town %}
                      {% for error in error.Town %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div> -->
                  <!-- <div class="form-group">
                    {{form.Address1.label}}
                    {{form.Address1}}
                    {% if error.Address1 %}
                      {% for error in error.Address1 %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div> -->
                  <div class="form-group">
                    {{form.Address.label}}
                    {{form.Address}}
                    {% if error.Address %}
                      {% for error in error.Address %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>Location Info</b></label>
                  <div class="form-group">
                    {{form.Provinsi.label}}
                    {{form.Provinsi}}
                    {% if error.Provinsi %}
                      {% for error in error.Provinsi %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kabupaten.label}}
                    {{form.Kabupaten}}
                    {% if error.Kabupaten %}
                      {% for error in error.Kabupaten %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kecamatan.label}}
                    {{form.Kecamatan}}
                    {% if error.Kecamatan %}
                      {% for error in error.Kecamatan %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kelurahan.label}}
                    {{form.Kelurahan}}
                    {% if error.Kelurahan %}
                      {% for error in error.Kelurahan %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Latitude.label}}
                    {{form.Latitude}}
                    {% if error.Latitude %}
                      {% for error in error.Latitude %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Longitude.label}}
                    {{form.Longitude}}
                    {% if error.Longitude %}
                      {% for error in error.Longitude %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>Delivery Info</b></label>
                  <div class="form-group">
                    {{form.Days.label}}
                    {{form.Days}}
                    {% if error.Days %}
                      {% for error in error.Days %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Delivery.label}}
                    {{form.Delivery}}
                    {% if error.Delivery %}
                      {% for error in error.Delivery %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
            </div>
            <div class="card-action">
              <button class="btn btn-success" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}

app_outlet/templates/outlet/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load custom_tags %}

{% block content_header %}
<div class="page-header">
  <h3 class="fw-bold mb-3">{{PageHeader}}</h3>
  <ul class="breadcrumbs mb-3">
    <li class="nav-home">
      <a href="{% url breadcrumbs.dashboard.url %}">
        <i class="icon-home"></i>
      </a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a href="{% url breadcrumbs.outlet.index.url %}">{{breadcrumbs.outlet.index.name}}</a>
    </li>
  </ul>
</div>
{% endblock content_header %}

{% block style_app %}
<style>
table td .btn{
  width: 100%;
  margin: 0
}
table td .btn:nth-child(1){
  margin-bottom: 10px
}
table th, td{
  text-align: center;
  vertical-align: middle;
}
</style>
{% endblock style_app %}

{% block Content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <h4 class="card-title">Add Row</h4>
          
          {% if user|has_group:"Admin" %}
          <a class="ms-auto" href="{% url link %}">
            <button class="btn btn-secondary" >
              <i class="fa fa-plus"></i>
              {{linkButton}}
            </button>
          </a>
          {%endif%}
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table
            id="add-row"
            class="display table table-striped table-hover"
          >
            <thead>
              <tr>
                <th scope="col">No.</th>
                <!-- <th scope="col">Outlet Code</th> -->
                <th scope="col">Outet Name</th>
                <th scope="col">Outlet Type</th>
                <!-- <th scope="col">Provinsi</th> -->
                <th scope="col">Kabupaten/Kota</th>
                <th scope="col">Kecamatan</th>
                <th scope="col">Kelurahan</th>
                <th scope="col">PJP Day</th>
                <th scope="col" style="width: 10%">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for data in OutletDatas %}
                  <tr>
                    <td scope="row">{{forloop.counter}}</td>
                    <!-- <td>{{data.OutletCode}}</td> -->
                    <td>{{data.OutletName}}</td>
                    <td>{{data.OutletType}}</td>
                    <!-- <td>{{data.Provinsi}}</td> -->
                    <td>{{data.Kabupaten}}</td>
                    <td>{{data.Kecamatan}}</td>
                    <td>{{data.Kelurahan}}</td>
                    <td>{{data.Days}}</td>
                    <td>
                      <a href="{% url "app_outlet:outletView" outletCode=data.OutletCode %}">
                        <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-secondary" data-original-title="View Task">
                            View
                        </button>
                      </a>
                      
                      {% if user|has_group:"Admin" %}
                        <a href="{% url 'app_outlet:outletUpdate' outletCode=data.OutletCode %}"> 
                          <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-secondary" data-original-title="Edit Task">
                              Edit
                          </button>
                        </a>
                        <button 
                          type="button" 
                          class="btn btn-danger" 
                          data-bs-toggle="modal" 
                          data-bs-target="#deleteModal" 
                          data-url="{% url 'app_outlet:outletDelete' outletCode=data.OutletCode %}">
                          Delete
                      </button>
                      {%endif%}
                    </td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Konfirmasi Hapus -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Konfirmasi Penghapusan</h5>
          </div>
          <div class="modal-body">
              Apakah Anda yakin ingin menghapus data ini? Tindakan ini tidak dapat dibatalkan.
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tidak</button>
              <button type="button" class="btn btn-danger" id="confirmDelete">Ya, Hapus</button>
          </div>
      </div>
  </div>
</div>

{% endblock Content %}

{% block scripts_app %}

<!-- Datatables -->
<script src="{% static '/assets/js/plugin/datatables/datatables.min.js' %}"></script>
<script>
    $(document).ready(function () {
      var deleteUrl = '';

      // Atur URL hapus saat modal ditampilkan
      document.getElementById('deleteModal').addEventListener('show.bs.modal', function (event) {
          var button = event.relatedTarget; // Tombol yang memicu modal
          deleteUrl = button.getAttribute('data-url'); // Mengambil data-url dari tombol
      });

      // Hapus data saat pengguna mengkonfirmasi
      document.getElementById('confirmDelete').addEventListener('click', function() {
          window.location.href = deleteUrl;
      });
      
      $("#basic-datatables").DataTable({});
      $("#basic-datatables2").DataTable({});

      $("#multi-filter-select").DataTable({
        pageLength: 5,
        initComplete: function () {
          this.api()
            .columns()
            .every(function () {
              var column = this;
              var select = $(
                '<select class="form-select"><option value=""></option></select>'
              )
                .appendTo($(column.footer()).empty())
                .on("change", function () {
                  var val = $.fn.dataTable.util.escapeRegex($(this).val());

                  column
                    .search(val ? "^" + val + "$" : "", true, false)
                    .draw();
                });

              column
                .data()
                .unique()
                .sort()
                .each(function (d, j) {
                  select.append(
                    '<option value="' + d + '">' + d + "</option>"
                  );
                });
            });
        },
      });

      // Add Row
      $("#add-row").DataTable({
        pageLength: 5,
      });

      var action =
        '<td> <div class="form-button-action"> <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-link btn-secondary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

      $("#addRowButton").click(function () {
        $("#add-row")
          .dataTable()
          .fnAddData([
            $("#addName").val(),
            $("#addPosition").val(),
            $("#addOffice").val(),
            action,
          ]);
        $("#addRowModal").modal("hide");
      });
    });
  </script>
{% endblock scripts_app %}

app_outlet/templates/outlet/update.html
{% extends "layout/base.html" %}
{% load static %}

{% block content_header %}
<div class="page-header">
    <h3 class="fw-bold mb-3">Update Outlet</h3>
    <ul class="breadcrumbs mb-3">
      <li class="nav-home">
        <a href="{% url breadcrumbs.dashboard.url %}">
          <i class="icon-home"></i>
        </a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="{% url breadcrumbs.outlet.index.url %}">{{breadcrumbs.outlet.index.name}}</a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a>{{breadcrumbs.outlet.update.name}}</a>
      </li>
    </ul>
  </div>
{% endblock content_header %}

{% block Content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">Form Update Outlet</div>
        </div>
        <div class="card-body">
          <form action="" method="POST">
            <div class="row">
              {% csrf_token %}
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>General Info</b></label>
                  <div class="form-group">
                    {{form.OutletNumber.label}}
                    {{form.OutletNumber}}
                    {% if error.OutletNumber %}
                      {% for error in error.OutletNumber %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletCode.label}}
                    {{form.OutletCode}}
                    {% if error.OutletCode %}
                      {% for error in error.OutletCode %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletName.label}}
                    {{form.OutletName}}
                    {% if error.OutletName %}
                      {% for error in error.OutletName %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.OutletType.label}}
                    {{form.OutletType}}
                    {% if error.OutletType %}
                      {% for error in error.OutletType %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <!-- <div class="form-group">
                    {{form.Town.label}}
                    {{form.Town}}
                    {% if error.Town %}
                      {% for error in error.Town %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Address1.label}}
                    {{form.Address1}}
                    {% if error.Address1 %}
                      {% for error in error.Address1 %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div> -->
                  <div class="form-group">
                    {{form.Address.label}}
                    {{form.Address}}
                    {% if error.Address %}
                      {% for error in error.Address %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>Location Info</b></label>
                  <div class="form-group">
                    {{form.Provinsi.label}}
                    {{form.Provinsi}}
                    {% if error.Provinsi %}
                      {% for error in error.Provinsi %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kabupaten.label}}
                    {{form.Kabupaten}}
                    {% if error.Kabupaten %}
                      {% for error in error.Kabupaten %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kecamatan.label}}
                    {{form.Kecamatan}}
                    {% if error.Kecamatan %}
                      {% for error in error.Kecamatan %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Kelurahan.label}}
                    {{form.Kelurahan}}
                    {% if error.Kelurahan %}
                      {% for error in error.Kelurahan %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Latitude.label}}
                    {{form.Latitude}}
                    {% if error.Latitude %}
                      {% for error in error.Latitude %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Longitude.label}}
                    {{form.Longitude}}
                    {% if error.Longitude %}
                      {% for error in error.Longitude %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
              <div class="col-md-6 col-lg-4">
                  <label class="mb-3"><b>Delivery Info</b></label>
                  <div class="form-group">
                    {{form.Days.label}}
                    {{form.Days}}
                    {% if error.Days %}
                      {% for error in error.Days %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{form.Delivery.label}}
                    {{form.Delivery}}
                    {% if error.Delivery %}
                      {% for error in error.Delivery %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                  </div>
              </div>
            </div>
            <div class="card-action">
              <button class="btn btn-success" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}