app_user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name='app_user'
urlpatterns = [
    path('logout/', LogoutView.as_view(next_page='app_user:login'), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
    path('update/<str:userId>', views.update, name='userUpdate'),
    path('delete/<str:userId>', views.delete, name='userDelete'),
    path('index/', views.index, name='index'),
]

proweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', redirect('home/')),
    path('schedule/', include('app_schedules.urls', namespace='app_schedules')),
    path('vehicle/', include('app_vehicle.urls', namespace='app_vehicle')),
    path('outlet/', include('app_outlet.urls', namespace='app_outlet')),
    path('report/', include('app_report.urls', namespace='app_report')),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_dashboard.urls')),        #home
    path('admin/', admin.site.urls),
]

app_user/models.py
from django.db import models

# Create your models here.

app_user/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User, Group
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .form import RegisterForm, LoginForm, ProfileForm, UpdateForm, MyPasswordChangeForm
from proweb.decorators import group_required
from proweb.mixins import AdminRequiredMixin

@group_required('Admin')
def index(request):
    userObject = User.objects.prefetch_related('groups').all()
    context={
        'UserObject' : userObject
    }
    return render(request, 'user/index.html', context)

@group_required('Admin')
def update(request, userId):
    userObject = get_object_or_404(User, id=userId)
    print(userObject.groups.all())
    passwordForm = MyPasswordChangeForm(user=userObject, data=request.POST)
    userForm_updated = UpdateForm(request.POST or None, instance=userObject)
    # userForm_updated['group'].initial =userObject.groups.all()  # Set initial value untuk grup yang dipilih
    error=None
    if(request.method == 'POST'):
        if 'updateUser' in request.POST:
            if userForm_updated.is_valid():
                userForm_updated.save()
                print(userForm_updated.cleaned_data)  # Debugging
                userObject.groups.clear()  # Hapus semua grup yang ada
                userObject.groups.add(userForm_updated.cleaned_data['group'])  # Gunakan 'group' di sini
                messages.success(request, 'Your profile was successfully updated!')
                return redirect('app_user:index')
        elif 'changePassword' in request.POST:
            passwordForm = MyPasswordChangeForm(user=userObject, data=request.POST)
            if passwordForm.is_valid():
                user = passwordForm.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Your password was successfully updated!')
                return redirect('app_user:index')
            else:
                print(passwordForm.errors)
    context={
        'pageHeader' : "User's Update",
        'update_form':userForm_updated,
        'passwordForm':passwordForm,
        'error':error
    }
    return render(request, 'user/edit.html', context)

def delete(request, userId):
    user = get_object_or_404(User, id=userId)
    user.delete()
    return redirect('app_user:index')

@group_required('Admin', 'Driver')
def profile(request):
    profileForm = ProfileForm(instance=request.user)
    error=None
    if request.method == 'POST':
        if profileForm.is_valid():
            profileForm.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('app_user:profile')
        else:
           error = profileForm.errors
    context={
        'profileForm':profileForm,
        'error' : error
    }
    return render(request, 'user/profile.html', context)

class RegisterView(AdminRequiredMixin, View):
    def get(self, request):
        register_form = RegisterForm()
        context={
            'register_form' : register_form,
        }
        return render(request, 'user/register.html', context)
    
    def post(self, request):
        register_form = RegisterForm(request.POST or None)
        error={}
        print(request.POST)
        if register_form.is_valid() :
            user=register_form.save()
            group = register_form.cleaned_data['group']  # Ganti dengan nama grup yang sesuai
            user.groups.add(group)
            # Save group data and associate with user
            return redirect('app_user:index')
        else:
            print('failed')
            error=register_form.errors
        context={
            'register_form':register_form,
            'error':error
        }
        return render(request, 'user/register.html', context)
    
class LoginView(View):
    def get(self, request):
        form = LoginForm()
        context = {
            'form':form
        }
        return render(request, 'user/login.html', context)
    
    def post(self, request):
        form = LoginForm(data = request.POST)        
        context = {
            'form':form
        }
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                print('okee')
                user = form.get_user()
                login(request, user)
                return redirect('app_dashboard:home')
            else:
                messages.error(request, "You are not registered")
        else:
            messages.error(request, "Wrong Username or Wrong Password.")
        return render(request, 'user/login.html', context)

app_user/templates/user/edit.html
{% extends "layout/base.html" %}
{% load static %}

{% block content_header %}
<div class="page-header">
    <h3 class="fw-bold mb-3">Edit User</h3>
    <ul class="breadcrumbs mb-3">
      <li class="nav-home">
        <a href="#">
          <i class="icon-home"></i>
        </a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">List of User</a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">Edit User</a>
      </li>
    </ul>
  </div>
{% endblock content_header %}



{% block Content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">{{pageHeader}} Form</div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6 col-lg-4">
              <form action="" method='POST'>
                {% csrf_token %}
                <label class="mb-3"><b>General Info</b></label>
                 <div class="form-group">
                    {{update_form.username.label}}
                    {{update_form.username}}
                    {% if update_form.username.errors %}
                      {% for error in update_form.username.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{update_form.email.label}}
                    {{update_form.email}}
                    {% if update_form.email.errors %}
                      {% for error in update_form.email.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{update_form.group.label}}
                    {{update_form.group}}
                    {% if update_form.group.errors %}
                      {% for error in update_form.group.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <button class="btn btn-success" name="updateUser" type="submit">Submit</button>
                <!-- <button 
                    type="button" 
                    class="btn btn-danger" 
                    data-bs-toggle="modal" 
                    data-bs-target="#Modal" 
                    data-url="">
                    Change Password
                </button> -->
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Change Password</h5>
        </div>
          <div class="modal-body">
            <form action="" method='POST'>
              {% csrf_token %}
              {{ passwordForm.as_p }}
              
              <div class="form-group">
                <label>
                  <input type="checkbox" id="showPassword"> 
                  Show Password
                </label>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <button type="submit" name="changePassword" class="btn btn-danger" id="Confirm">Change Password</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}

{% block scripts_app %}
<script>
  $(document).ready(function () {
    document.getElementById('showPassword').addEventListener('change', function() {
      var oldpassword = document.getElementById('id_old_password');
      var password1 = document.getElementById('id_new_password1');
      var password2 = document.getElementById('id_new_password2');
      if (this.checked) {
          oldpassword.type = 'text'
          password1.type = 'text';
          password2.type = 'text';
      } else {
          oldpassword.type = 'password'
          password1.type = 'password';
          password2.type = 'password';
      }
    });
    var deleteUrl = '';
    
    // Atur URL hapus saat modal ditampilkan
    document.getElementById('Modal').addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Tombol yang memicu modal
    });

    
  });
</script>

{% endblock scripts_app %}

app_user/templates/user/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load custom_tags %}

{% block style_app %}
<style>
table .vehicle .btn:nth-child(2){
  margin-left: 10px
}

table .driver a{
  width: 100%;
  margin-right: 10px;
}

table th, td{
  text-align: center;
  vertical-align: middle;
}
</style>
{% endblock style_app %}

{% block content_header %}
<div class="page-header">
  <h3 class="fw-bold mb-3">User</h3>
  <ul class="breadcrumbs mb-3">
    <li class="nav-home">
      <a href="#">
        <i class="icon-home"></i>
      </a>
    </li>
    <li class="separator">
      <i class="icon-arrow-right"></i>
    </li>
    <li class="nav-item">
      <a href="#">List of User</a>
    </li>
  </ul>
  <!-- <button id="generate-schedule-btn" class="btn btn-secondary btn-round ms-auto">
    Finish
  </button> -->
</div>
{% endblock content_header %}

{% block Content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <h4 class="card-title">List of User</h4>
          <a class="ms-auto" href="{% url 'app_user:register' %}">
            <button class="btn btn-secondary btn-round" >
              <i class="fa fa-plus"></i>
              Add User
            </button>
          </a>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">            
          <table id="basic-datatables" class="display table table-striped table-hover" >
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Username</th>
                <th scope="col">Group</th>
                <th scope="col">Email</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for UserDatas in UserObject %}
              <tr>
                <td scope="'row">{{forloop.counter}}</td>
                <td>{{UserDatas.username}}</td>
                {% for group in UserDatas.groups.all %}
                  <td>{{group.name}}</td>
                  {% if not forloop.last %}, 
                  {% endif %} 
                  {% empty %}
                  <td>Tidak ada grup</td>  <!-- Jika user tidak tergabung dalam grup -->
                {% endfor %}
                
                <td>{{UserDatas.email}}</td>
                
                <td class="d-flex vehicle">
                  <a href="{% url 'app_user:userUpdate' userId=UserDatas.id %}">
                    <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-secondary" data-original-title="Edit Task">
                      Edit
                    </button>
                  </a>
                  <button 
                      type="button" 
                      class="btn btn-danger" 
                      data-bs-toggle="modal" 
                      data-bs-target="#deleteModal" 
                      data-url="{% url 'app_user:userDelete' userId=UserDatas.id %}">
                      Delete
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Konfirmasi Hapus -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Konfirmasi Penghapusan</h5>
          </div>
          <div class="modal-body">
              Apakah Anda yakin ingin menghapus data ini? Tindakan ini tidak dapat dibatalkan.
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tidak</button>
              <button type="button" class="btn btn-danger" id="confirmDelete">Ya, Hapus</button>
          </div>
      </div>
  </div>
</div>

{% endblock Content %}

{% block scripts_app %}
<!-- Datatables -->
<script src="{% static '/assets/js/plugin/datatables/datatables.min.js' %}"></script>
<script>
  $(document).ready(function () {
    var deleteUrl = '';

    // Atur URL hapus saat modal ditampilkan
    document.getElementById('deleteModal').addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Tombol yang memicu modal
        deleteUrl = button.getAttribute('data-url'); // Mengambil data-url dari tombol
    });

    // Hapus data saat pengguna mengkonfirmasi
    document.getElementById('confirmDelete').addEventListener('click', function() {
        window.location.href = deleteUrl;
    });

    $("#basic-datatables").DataTable({});

  });
  </script>
{% endblock scripts_app %}

app_user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Rubik:400,700'>
    <link rel="stylesheet" href="{% static '/custom/css/login.css' %}">
</head>
<body>
    <div class="login-form">
        <form method="post">
            {% csrf_token %}    
            <h1>Login</h1>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger my-0">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="content">
                <div class="input-field">
                    {{form.username}}
                </div>
                <div class="input-field">
                    {{form.password}}
                </div>
            </div>
            <div class="action">
            <button type="submit">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

app_user/templates/user/profile.html
{% extends "layout/base.html" %}
{% load static %}

{% block content_header %}
<div class="page-header">
    <h3 class="fw-bold mb-3">{{pageHeader}}</h3>
    <ul class="breadcrumbs mb-3">
      <li class="nav-home">
        <a href="#">
          <i class="icon-home"></i>
        </a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">Vehicles & Driver Overview</a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">{{pageHeader}}</a>
      </li>
    </ul>
  </div>
{% endblock content_header %}

{% block messages %}
  <div id="flashMessages" class="flash-messages bootstrap-alert">
      {% if messages %}
          {% for message in messages %}
                <div style="background-color:#d4edda; color:#155724;" class="alert alert-success" role="alert">
                    {{ message }}
                </div>
          {% endfor %}
      {% endif %}
  </div>
{% endblock messages %}

{% block Content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">{{pageHeader}} Form</div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6 col-lg-4">
              <form action="" method='POST'>
                {% csrf_token %}
                {% for field in profileForm %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{field}}
                    {% for error in field.errors %}
                      
                        <span class="errorlist">{{error}}</span>
                    {% endfor %}
                  </div>
                {% endfor %}
                <button class="btn btn-success" type="submit">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}

{% block scripts_app %}
<script>
  $(document).ready(function () {
    
    var deleteUrl = '';
    
    // Atur URL hapus saat modal ditampilkan
    document.getElementById('Modal').addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Tombol yang memicu modal
    });

    const flashMessages = document.getElementById('flashMessages');
    if (flashMessages) {
        setTimeout(function() {
            flashMessages.style.opacity = '0';
            setTimeout(function() {
                flashMessages.remove();
            }, 500); // Hapus elemen setelah transisi selesai
        }, 3000); // Waktu tampil 3000 ms atau 3 detik
    }
    
    $("#basic-datatables").DataTable({});

  });
  </script>

{% endblock scripts_app %}

app_user/templates/user/register.html
{% extends "layout/base.html" %}
{% load static %}

{% block content_header %}
<div class="page-header">
    <h3 class="fw-bold mb-3">Add User</h3>
    <ul class="breadcrumbs mb-3">
      <li class="nav-home">
        <a href="#">
          <i class="icon-home"></i>
        </a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">List of User</a>
      </li>
      <li class="separator">
        <i class="icon-arrow-right"></i>
      </li>
      <li class="nav-item">
        <a href="#">Add User</a>
      </li>
    </ul>
  </div>
{% endblock content_header %}

{% block Content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">{{pageHeader}} Form</div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6 col-lg-4">
              <form action="" method='POST'>
                {% csrf_token %}
                <label class="mb-3"><b>General Info</b></label>
                 <div class="form-group">
                    {{register_form.username.label}}
                    {{register_form.username}}
                    {% if register_form.username.errors %}
                      {% for error in register_form.username.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{register_form.email.label}}
                    {{register_form.email}}
                    {% if register_form.email.errors %}
                      {% for error in register_form.email.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{register_form.group.label}}
                    {{register_form.group}}
                    {% if register_form.group.errors %}
                      {% for error in register_form.group.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{register_form.password1.label}}
                    {{register_form.password1}}
                    {% if register_form.password1.errors %}
                      {% for error in register_form.password1.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{register_form.password2.label}}
                    {{register_form.password2}}
                    {% if register_form.password2.errors %}
                      {% for error in register_form.password2.errors %}
                        <span class="errorlist">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                  <label>
                    <input type="checkbox" id="showPassword"> 
                    Show Password
                  </label>
                </div>
                <div class="card-action">
                  <button class="btn btn-success" type="submit">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}

{% block scripts_app %}
<script>
  $(document).ready(function () {
    document.getElementById('showPassword').addEventListener('change', function() {
    var password1 = document.getElementById('id_password1');
    var password2 = document.getElementById('id_password2');
    if (this.checked) {
        password1.type = 'text';
        password2.type = 'text';
    } else {
        password1.type = 'password';
        password2.type = 'password';
    }
  });
})
</script>

{% endblock scripts_app %}