app_dashboard/urls.py
from django.urls import path
from . import views

app_name="app_dashboard"
urlpatterns = [
    path('', views.index, name='home'),
]

app_outlet/urls.py
from django.urls import path
from . import views

app_name="app_outlet"
urlpatterns = [
    path('', views.outlet_index, name='outletIndex'),
    path('create/', views.outlet_create, name='outletCreate'),
    path('update/<str:outletCode>', views.outlet_update, name='outletUpdate'),
    path('view/<str:outletCode>', views.outlet_view, name='outletView'),
    path('delete/<str:outletCode>', views.outlet_delete, name='outletDelete'),
]

app_user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name='app_user'
urlpatterns = [
    path('logout/', LogoutView.as_view(next_page='app_user:login'), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
    path('update/<str:userId>', views.update, name='userUpdate'),
    path('delete/<str:userId>', views.delete, name='userDelete'),
    path('index/', views.index, name='index'),
]

app_vehicle/urls.py
from django.urls import path
from . import views

app_name='app_vehicle'
urlpatterns = [
        
    path('', views.vehicle_index, name='vehicleIndex'),
    path('create', views.vehicle_create, name='vehicleCreate'),
    path('update/<str:vehicleNumber>', views.vehicle_update, name='vehicleUpdate'),
    path('delete/<str:vehicleNumber>', views.vehicle_delete, name='vehicleDelete'),
    
    # path('driver/create', views.driver_create, name='driverCreate'),
    # path('driver/update/<str:driverId>', views.driver_update, name='driverUpdate'),
    # path('driver/view/<str:driverId>', views.driver_view, name='driverView'),
    # path('driver/delete/<str:driverId>', views.driver_delete, name='driverDelete'),
]

proweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', redirect('home/')),
    path('schedule/', include('app_schedules.urls', namespace='app_schedules')),
    path('vehicle/', include('app_vehicle.urls', namespace='app_vehicle')),
    path('outlet/', include('app_outlet.urls', namespace='app_outlet')),
    path('report/', include('app_report.urls', namespace='app_report')),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_dashboard.urls')),        #home
    path('admin/', admin.site.urls),
]

templates/includes/footer.html
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
      <nav class="pull-left">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="http://www.themekita.com">
              ThemeKita
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Help </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Licenses </a>
          </li>
        </ul>
      </nav>
      <div class="copyright">
        2024, made with <i class="fa fa-heart heart text-danger"></i> by
        <a href="http://www.themekita.com">ThemeKita</a>
      </div>
      <div>
        Distributed by
        <a target="_blank" href="https://themewagon.com/">ThemeWagon</a>.
      </div>
    </div>
  </footer>

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
<div class="container-fluid">
  <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
      <p class="my-0 fw-bold fs-3">{{day_name}}, {{current_date}}</p>
  </nav>
  <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
    <li class="nav-item topbar-user dropdown hidden-caret">
      <a
        class="dropdown-toggle profile-pic"
        data-bs-toggle="dropdown"
        href="#"
        aria-expanded="false"
      >
        <!-- <div class="avatar-sm">
          <img
            src="{% static 'assets/img/profile.jpg' %}"
            alt="..."
            class="avatar-img rounded-circle"
          />
        </div> -->
        <span class="profile-username">
          User: 
          <span class="fw-bold">{{user.username}}</span>
        </span>
      </a>
      <ul class="dropdown-menu dropdown-user animated fadeIn">
        <div class="dropdown-user-scroll scrollbar-outer">
          <li>
            <div class="user-box">
              <div class="avatar-lg">
                <img
                  src="{% static 'assets/img/profile.jpg' %}"
                  alt="image profile"
                  class="avatar-img rounded"
                />
              </div>
              <div class="u-text">
                <h4>Welcome</h4>
                <p class="text-muted">{{user.username}}</p>
                <p class="text-muted">{{user.email}}</p>
              </div>
            </div>
          </li>
          <li>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url "app_user:profile"%}">View Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" onclick="document.getElementById('logout-form').submit(); return false;">
              Logout
            </a>
            <form id="logout-form" method="post" action="{% url 'app_user:logout' %}" style="display: none;">
              {% csrf_token %}
            </form>
          </li>
        </div>
      </ul>
    </li>
  </ul>
</div>
</nav>

templates/includes/scripts.html
{% load static %}
<script src="{% static '/assets/js/core/jquery-3.7.1.min.js' %}"></script>
<script src="{% static '/assets/js/core/popper.min.js' %}"></script>
<script src="{% static '/assets/js/core/bootstrap.min.js' %}"></script>

<!-- jQuery Scrollbar -->
<script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

<!-- Chart JS -->
<script src="{% static 'assets/js/plugin/chart.js/chart.min.js' %}"></script>

<!-- jQuery Sparkline -->
<script src="{% static 'assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Chart Circle -->
<script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

<!-- Bootstrap Notify -->
<script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

<!-- jQuery Vector Maps -->
<script src="{% static 'assets/js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jsvectormap/world.js' %}"></script>

<!-- Sweet Alert -->
<script src="{% static 'assets/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

<!-- Kaiadmin JS -->
<script src="{% static 'assets/js/kaiadmin.min.js' %}"></script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Ambil URL dari halaman saat ini
        var currentUrl = window.location.pathname;
        console.log("URL saat ini:", currentUrl); // Debug: cek URL saat ini
    
        // Ambil semua elemen <a> dalam navigasi
        var menuItems = document.querySelectorAll("nav ul li a");
    
        // Loop melalui setiap elemen <a> untuk mencocokkan URL saat ini
        menuItems.forEach(function(item) {
            console.log("Memeriksa href:", item.getAttribute("href")); // Debug: cek setiap href
    
            if (item.getAttribute("href") === currentUrl) {
                console.log("Menemukan kecocokan:", item.getAttribute("href")); // Debug: konfirmasi kecocokan
                // Tambahkan kelas 'active' pada parent <li> jika URL cocok
                item.parentElement.classList.add("active");
            }
        });
    });
</script>

<script>
$(document).ready(function () {
    const flashMessages = document.getElementById('flashMessages');
    if (flashMessages) {
        setTimeout(function() {
            flashMessages.style.opacity = '0';
            setTimeout(function() {
                flashMessages.remove();
            }, 500); // Hapus elemen setelah transisi selesai
        }, 3000); // Waktu tampil 3000 ms atau 3 detik
    }
});
</script>

templates/includes/settings.html
<div class="custom-template">
    <div class="title">Settings</div>
    <div class="custom-content">
      <div class="switcher">
        <div class="switch-block">
          <h4>Logo Header</h4>
          <div class="btnSwitch">
            <button
              type="button"
              class="selected changeLogoHeaderColor"
              data-color="dark"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="blue"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="purple"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="light-blue"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="green"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="orange"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="red"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="white"
            ></button>
            <br />
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="dark2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="blue2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="purple2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="light-blue2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="green2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="orange2"
            ></button>
            <button
              type="button"
              class="changeLogoHeaderColor"
              data-color="red2"
            ></button>
          </div>
        </div>
        <div class="switch-block">
          <h4>Navbar Header</h4>
          <div class="btnSwitch">
            <button
              type="button"
              class="changeTopBarColor"
              data-color="dark"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="blue"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="purple"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="light-blue"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="green"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="orange"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="red"
            ></button>
            <button
              type="button"
              class="selected changeTopBarColor"
              data-color="white"
            ></button>
            <br />
            <button
              type="button"
              class="changeTopBarColor"
              data-color="dark2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="blue2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="purple2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="light-blue2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="green2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="orange2"
            ></button>
            <button
              type="button"
              class="changeTopBarColor"
              data-color="red2"
            ></button>
          </div>
        </div>
        <div class="switch-block">
          <h4>Sidebar</h4>
          <div class="btnSwitch">
            <button
              type="button"
              class="changeSideBarColor"
              data-color="white"
            ></button>
            <button
              type="button"
              class="selected changeSideBarColor"
              data-color="dark"
            ></button>
            <button
              type="button"
              class="changeSideBarColor"
              data-color="dark2"
            ></button>
          </div>
        </div>
      </div>
    </div>
    <div class="custom-toggle">
      <i class="icon-settings"></i>
    </div>
  </div>

templates/includes/sidebar.html
{% load static %}
{% load custom_tags %}

<div class="sidebar" data-background-color="dark">
    <div class="sidebar-logo">
      <!-- Logo Header -->
      <div class="logo-header" data-background-color="white">
        <a href="{% url 'app_dashboard:home' %}" class="logo">
          <img
            src="{% static 'assets/img/kalla-logistic-logo.png' %}"
            alt="navbar brand"
            class="navbar-brand"
            height="60"
          />
        </a>
        <div class="nav-toggle">
          <button class="btn btn-toggle toggle-sidebar">
            <i class="gg-menu-right"></i>
          </button>
          <button class="btn btn-toggle sidenav-toggler">
            <i class="gg-menu-left"></i>
          </button>
        </div>
        <button class="topbar-toggler more">
          <i class="gg-more-vertical-alt"></i>
        </button>
      </div>
      <!-- End Logo Header -->
    </div>
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
      <div class="sidebar-content">
        <ul class="nav nav-secondary">
            
          <li class="nav-item {% if current_namespace == 'app_dashboard' %}active{% endif %}">
            <a
              href="{% url 'app_dashboard:home' %}"
            >
              <i class="fas fa-home"></i>
              <p>Dashboard</p>
            </a>
          </li>
          
          <li class="nav-item {% if current_namespace == 'app_outlet' %}active{% endif %}">
            <a
              href="{% url 'app_outlet:outletIndex' %}"
            >
              <i class="fas fa-building"></i>
              <p>Outlets</p>
            </a>
          </li>
          <li class="nav-item {% if current_namespace == 'app_vehicle' %}active{% endif %}">
            <a
              href="{% url 'app_vehicle:vehicleIndex' %}"
            >
              <i class="fas fa-truck"></i>
              <p>Vehicles & Drivers</p>
            </a>
          </li>
          {% if user|has_group:"Admin" %}
          <li class="nav-item {% if current_namespace == 'app_schedules' %}active{% endif %}">
            <a
              href="{% url 'app_schedules:index' %}"
            >
              <i class="fas fa-calendar-alt"></i>
              <p>Schedule</p>
            </a>
          </li>
          {% endif %}
          <li class="nav-item {% if current_namespace == 'app_report' %}active{% endif %}">
            <a
              href="{% url "app_report:index" %}"
            >
              <i class="fas fa-file"></i>
              <p>Report</p>
            </a>
          </li>
          {% if user|has_group:"Admin" %}
          <li class="nav-item {% if current_namespace == 'app_user' %}active{% endif %}">
            <a
              href="{% url "app_user:index" %}"
            >
              <i class="fas fa-user"></i>
              <p>User</p>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>

templates/includes/styles.html
{% load static %}
<link rel="icon" href="{% static '/assets/img/kaiadmin/favicon.ico' %}" type="image/x-icon"/>
<!-- Fonts and icons -->
<script src="{% static '/assets/js/plugin/webfont/webfont.min.js' %}"></script>
<script> WebFont.load({
    google: { families: ["Public Sans:300,400,500,600,700"] },
    custom: {
        families: [
        "Font Awesome 5 Solid",
        "Font Awesome 5 Regular",
        "Font Awesome 5 Brands",
        "simple-line-icons",
        ],
        urls: ["{% static '/assets/css/fonts.min.css' %}"],
    },
    active: function () {
        sessionStorage.fonts = true;
    },
    });
</script>

<!-- CSS Files -->
<link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static '/assets/css/plugins.min.css' %}">
<link rel="stylesheet" href="{% static '/assets/css/kaiadmin.min.css' %}">
<link rel="stylesheet" href="{% static '/custom/css/styles.css' %}">